// archivus-svelte/src/lib/components/ProjectTable.svelte
<script lang="ts">
	import type { Project } from '$lib/api/todo';
	import { createEventDispatcher } from 'svelte';
	import { Folder } from 'lucide-svelte';

	export let projects: Project[] = [];
	export let selectedProjectId: number | undefined = undefined;

	const dispatch = createEventDispatcher<{ select: number | undefined }>();

	function select(id: number | undefined) {
		dispatch('select', id);
	}
</script>

<div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
	<!-- "Others" card -->
	<button
		on:click={() => select(undefined)}
		class="flex flex-col items-center gap-2 rounded-xl border p-4 text-sm font-medium
			transition-all hover:shadow-md
			{selectedProjectId === undefined
			? 'border-indigo-500 bg-indigo-50 text-indigo-700'
			: 'border-gray-200 bg-white text-gray-600 hover:border-gray-300'}"
	>
		<Folder class="h-8 w-8 {selectedProjectId === undefined ? 'text-indigo-500' : 'text-gray-400'}" />
		Others
	</button>

	{#each projects as project (project.id)}
		<button
			on:click={() => select(project.id)}
			class="flex flex-col items-center gap-2 rounded-xl border p-4 text-sm font-medium
				transition-all hover:shadow-md
				{selectedProjectId === project.id
				? 'border-indigo-500 bg-indigo-50 text-indigo-700'
				: 'border-gray-200 bg-white text-gray-600 hover:border-gray-300'}"
		>
			<Folder
				class="h-8 w-8 {selectedProjectId === project.id ? 'text-indigo-500' : 'text-gray-400'}"
			/>
			<span class="truncate w-full text-center" title={project.title}>{project.title}</span>
		</button>
	{/each}
</div>

// archivus-client/app/ui/projectTable.tsx
import { EnvelopeIcon, PhoneIcon } from '@heroicons/react/20/solid'
import { Project } from '../api/todo'


export default function ProjectTable({projects, onChange}: {projects: Project[], onChange: (id?: number) => void}) { 
  return (
    <ul role="list" className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
      {projects && projects.map((p) => (
        <li key={p.id} className="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow-sm">
        <button onClick={() => onChange(p.id)} className="w-full">
          <div className="flex w-full items-center justify-between space-x-6 p-6">
            <div className="flex-1 truncate">
              <div className="flex items-center space-x-3">
                <h3 className="truncate text-sm font-medium text-gray-900">{p.title}</h3>
              </div>
            </div>
          </div>
          <div>
          </div>
        </button>
        </li>
      ))}
      <li className="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow-sm">
        <button onClick={() => onChange()} className="w-full">
          <div className="flex w-full items-center justify-between space-x-6 p-6">
            <div className="flex-1 truncate">
              <div className="flex items-center space-x-3">
                <h3 className="truncate text-sm font-medium text-gray-900">Others</h3>
              </div>
            </div>
          </div>
          <div>
          </div>
          </button>
        </li>
    </ul>
  )
}
