// archivus-svelte/src/lib/components/TodoTable.svelte
<script lang="ts">
	import type { Todo } from '$lib/api/todo';
	import { updateTodoStatus } from '$lib/api/todo';
	import { CheckSquare, Square, AlertCircle, Minus, ArrowUp } from 'lucide-svelte';
	import { createEventDispatcher } from 'svelte';

	export let todos: Todo[] = [];

	const dispatch = createEventDispatcher<{ refresh: void }>();

	const STATUS_LABELS: Record<number, string> = {
		0: 'Not Done',
		1: 'In Progress',
		2: 'Done'
	};

	const PRIORITY_LABELS: Record<number, { label: string; color: string }> = {
		0: { label: 'Low', color: 'text-green-600 bg-green-50' },
		1: { label: 'Medium', color: 'text-yellow-600 bg-yellow-50' },
		2: { label: 'High', color: 'text-red-600 bg-red-50' }
	};

	async function toggleStatus(todo: Todo) {
		const nextStatus = todo.status === 2 ? 0 : todo.status + 1;
		try {
			await updateTodoStatus(todo.id, nextStatus);
			dispatch('refresh');
		} catch (err) {
			alert('Failed to update: ' + (err as Error).message);
		}
	}
</script>

{#if todos.length === 0}
	<p class="py-12 text-center text-sm text-gray-400">No todos yet.</p>
{:else}
	<div class="overflow-x-auto rounded-xl border border-gray-200">
		<table class="min-w-full divide-y divide-gray-200">
			<thead class="bg-gray-50">
				<tr>
					<th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500 w-10"></th>
					<th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">Title</th>
					<th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">Priority</th>
					<th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">Status</th>
				</tr>
			</thead>
			<tbody class="divide-y divide-gray-100 bg-white">
				{#each todos as todo (todo.id)}
					<tr class="hover:bg-gray-50 transition-colors">
						<td class="px-4 py-3">
							<button
								on:click={() => toggleStatus(todo)}
								class="text-gray-400 hover:text-indigo-600 transition-colors"
								title="Toggle status"
							>
								{#if todo.status === 2}
									<CheckSquare class="h-5 w-5 text-indigo-500" />
								{:else}
									<Square class="h-5 w-5" />
								{/if}
							</button>
						</td>
						<td class="px-4 py-3 text-sm font-medium text-gray-800 {todo.status === 2 ? 'line-through text-gray-400' : ''}">
							{todo.title}
						</td>
						<td class="px-4 py-3">
							{#if todo.priority !== undefined}
								{@const p = PRIORITY_LABELS[todo.priority] ?? { label: 'Unknown', color: 'text-gray-500 bg-gray-50' }}
								<span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium {p.color}">
									{p.label}
								</span>
							{/if}
						</td>
						<td class="px-4 py-3 text-sm text-gray-500">
							{STATUS_LABELS[todo.status] ?? ''}
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
{/if}

// archivus-client/app/ui/todoTable.tsx
import { Todo, updateTodo } from "../api/todo";

const StatusMap: { [key: number]: string } = {
    0: "Not Done",
    1: "In Progress",
    2: "Done"
}

const PriorityMap: { [key: number]: string } = {
    0: "Low",
    1: "Medium",
    2: "High"
}

export default function TodoTable({todos}: {todos: Todo[]}) {
    function handleClick(id: number) {
        updateTodo(id);
        window.location.reload();
    }
    return (
        <div className="mt-8 flow-root">
        <div className="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div className="inline-block min-w-full py-2 align-middle">
            <table className="relative min-w-full divide-y divide-gray-300">
              <thead>
                <tr>
                  <th
                    scope="col"
                    className="py-3.5 pr-3 pl-4 text-left text-sm font-semibold text-gray-900 sm:pl-6 lg:pl-8"
                  >
                    Title
                  </th>
                  <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                    Priority
                  </th>
                  <th scope="col" className="py-3.5 pr-4 pl-3 sm:pr-6 lg:pr-8">
                    <span className="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200 bg-white">
                {todos && todos.map((td) => (
                  <tr key={td.id}>
                    <td className="py-4 pr-3 pl-4 text-sm font-medium whitespace-nowrap text-gray-900 sm:pl-6 lg:pl-8">
                      {td.title}
                    </td>
                    <td className="px-3 py-4 text-sm whitespace-nowrap text-gray-500">{PriorityMap[td.priority]}</td>
                    <td className="py-4 pr-4 pl-3 text-right text-sm font-medium whitespace-nowrap sm:pr-6 lg:pr-8">
                      <button
                            type="button"
                            onClick={(e) => {handleClick(td.id)}}
                            aria-pressed={td.status === 2}
                            aria-label={td.status!=2 ? "Mark as not done" : "Mark as done"}
                            className={`inline-flex items-center justify-center w-10 h-10 rounded-full transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-400
                                ${td.status === 2 ? "bg-green-500 border-transparent shadow-sm" : "bg-white border-2 border-gray-200"}`}
                            >
                            {td.status === 2 ? (
                                <svg className="w-5 h-5 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                                <path d="M20 6L9 17l-5-5" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                                </svg>
                            ) : (
                                <svg className="w-5 h-5 text-gray-500" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                                <circle cx="12" cy="12" r="9" strokeWidth="2"></circle>
                                </svg>
                            )}
                            </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    )

}
