// archivus-svelte/src/lib/components/FileFolderModal.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import { Plus, Upload, FolderPlus, X } from 'lucide-svelte';
	import { uploadFiles } from '$lib/api/files';
	import { createFolder } from '$lib/api/folder';

	export let currentFolder: string = '';

	const dispatch = createEventDispatcher<{ refresh: void }>();

	let fabOpen = false;
	let uploadOpen = false;
	let folderOpen = false;

	let selectedFiles: FileList | null = null;
	let uploadProgress = 0;
	let uploading = false;

	let newFolderName = '';
	let creatingFolder = false;

	async function handleUpload() {
		if (!selectedFiles?.length) return;
		uploading = true;
		uploadProgress = 0;
		try {
			await uploadFiles(selectedFiles, currentFolder, (p) => (uploadProgress = p));
			uploadOpen = false;
			selectedFiles = null;
			uploadProgress = 0;
			dispatch('refresh');
		} catch (err) {
			alert('Upload failed: ' + (err as Error).message);
		} finally {
			uploading = false;
		}
	}

	async function handleCreateFolder() {
		if (!newFolderName.trim()) return;
		creatingFolder = true;
		try {
			const fullPath = currentFolder
				? `${currentFolder}/${newFolderName.trim()}`
				: newFolderName.trim();
			await createFolder(fullPath);
			folderOpen = false;
			newFolderName = '';
			dispatch('refresh');
		} catch (err) {
			alert('Failed to create folder: ' + (err as Error).message);
		} finally {
			creatingFolder = false;
		}
	}

	function closeAll() {
		fabOpen = false;
		uploadOpen = false;
		folderOpen = false;
	}
</script>

<!-- FAB -->
<div class="fixed bottom-6 right-6 z-40 flex flex-col items-end gap-3">
	{#if fabOpen}
		<!-- Upload option -->
		<button
			on:click={() => { uploadOpen = true; fabOpen = false; }}
			class="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-medium text-gray-700
				shadow-lg ring-1 ring-gray-200 hover:bg-gray-50 transition-colors"
		>
			<Upload class="h-4 w-4 text-indigo-500" />
			Upload files
		</button>

		<!-- New folder option -->
		<button
			on:click={() => { folderOpen = true; fabOpen = false; }}
			class="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-medium text-gray-700
				shadow-lg ring-1 ring-gray-200 hover:bg-gray-50 transition-colors"
		>
			<FolderPlus class="h-4 w-4 text-indigo-500" />
			New folder
		</button>
	{/if}

	<button
		on:click={() => (fabOpen = !fabOpen)}
		class="flex h-14 w-14 items-center justify-center rounded-full bg-indigo-600 text-white
			shadow-lg hover:bg-indigo-700 transition-all duration-200
			{fabOpen ? 'rotate-45' : 'rotate-0'}"
		aria-label="Actions"
	>
		<Plus class="h-7 w-7" />
	</button>
</div>

<!-- Click outside to close FAB -->
{#if fabOpen}
	<button
		class="fixed inset-0 z-30"
		aria-label="Close menu"
		on:click={() => (fabOpen = false)}
	></button>
{/if}

<!-- Upload Modal -->
{#if uploadOpen}
	<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm">
		<div class="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl">
			<div class="mb-4 flex items-center justify-between">
				<h2 class="text-lg font-semibold text-gray-900">Upload files</h2>
				<button on:click={() => (uploadOpen = false)} class="text-gray-400 hover:text-gray-600">
					<X class="h-5 w-5" />
				</button>
			</div>

			<input
				type="file"
				multiple
				on:change={(e) => (selectedFiles = (e.target as HTMLInputElement).files)}
				class="w-full rounded-lg border border-gray-300 text-sm text-gray-600
					file:mr-3 file:rounded-md file:border-0 file:bg-indigo-50 file:px-3 file:py-1.5
					file:text-sm file:font-medium file:text-indigo-700 hover:file:bg-indigo-100 mb-4"
			/>

			{#if uploading}
				<div class="mb-4">
					<div class="mb-1 flex justify-between text-xs text-gray-500">
						<span>Uploading...</span>
						<span>{uploadProgress}%</span>
					</div>
					<div class="h-2 w-full rounded-full bg-gray-200">
						<div
							class="h-2 rounded-full bg-indigo-500 transition-all"
							style="width: {uploadProgress}%"
						></div>
					</div>
				</div>
			{/if}

			<div class="flex justify-end gap-2">
				<button
					on:click={() => (uploadOpen = false)}
					disabled={uploading}
					class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700
						hover:bg-gray-50 disabled:opacity-50"
				>
					Cancel
				</button>
				<button
					on:click={handleUpload}
					disabled={!selectedFiles?.length || uploading}
					class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white
						hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed"
				>
					{uploading ? 'Uploading...' : 'Upload'}
				</button>
			</div>
		</div>
	</div>
{/if}

<!-- New Folder Modal -->
{#if folderOpen}
	<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm">
		<div class="w-full max-w-sm rounded-2xl bg-white p-6 shadow-xl">
			<div class="mb-4 flex items-center justify-between">
				<h2 class="text-lg font-semibold text-gray-900">New folder</h2>
				<button on:click={() => (folderOpen = false)} class="text-gray-400 hover:text-gray-600">
					<X class="h-5 w-5" />
				</button>
			</div>

			<input
				type="text"
				bind:value={newFolderName}
				placeholder="Folder name"
				on:keydown={(e) => e.key === 'Enter' && handleCreateFolder()}
				class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm
					focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 mb-4"
			/>

			<div class="flex justify-end gap-2">
				<button
					on:click={() => (folderOpen = false)}
					class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700
						hover:bg-gray-50"
				>
					Cancel
				</button>
				<button
					on:click={handleCreateFolder}
					disabled={!newFolderName.trim() || creatingFolder}
					class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white
						hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed"
				>
					{creatingFolder ? 'Creating...' : 'Create'}
				</button>
			</div>
		</div>
	</div>
{/if}

// archivus-client/app/ui/components/fileFolderModal.tsx
'use client'
import { useState, useRef } from "react";
import { Button } from "@/components/ui/button";
import { PlusIcon } from "lucide-react";
import { addFolder } from '@/app/api/folder';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription
} from "@/components/ui/dialog";
import { uploadFiles, uploadFilesWithProgress } from "@/app/api/files";
import { Progress } from "@/components/ui/progress";


export default function FileFolderDialog({ folder }: { folder: string }) {
  const [newFiles, setNewFiles] = useState<File[]>([]);
  const [modalType, setModalType] = useState<"files" | "folder" | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [newFolderName, setNewFolderName] = useState<string>("");
  const [uploading, setUploading] = useState<boolean>(false);
  const [progress, setProgress] = useState<number>(0);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const createFolder = async () => {
    try {
      if (folder !== '') {
        await addFolder(folder + '/' + newFolderName);
      } else {
        await addFolder(newFolderName);
      }
      alert("Folder created successfully");
    } catch (err) {
      console.error("Error creating folder:", err);
      alert("Error creating folder");
    }
  }

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {

    if (e.target.files) {
      setNewFiles(Array.from(e.target.files));
    }
  };

  const handleUpload = async (e: React.FormEvent) => {
    e.preventDefault();
    if (newFiles.length === 0) return;
    setUploading(true);
    setProgress(0);
    try {
      const res = await uploadFilesWithProgress(folder, newFiles, (p) => setProgress(p));
      if (!res) throw new Error("Upload failed");
      alert("Files uploaded successfully!");
      setNewFiles([]);
    } catch (err) {
      console.error(err);
      alert("Error uploading files");
    } finally {
      setUploading(false);
      setModalType(null);
      setProgress(0);
      window.location.reload();
    }
  };

  return (
    <>
      <div className="fixed bottom-6 right-6">
        <Button
          onClick={() => setDialogOpen(true)}
          className="rounded-full h-14 w-14 p-0 shadow-lg"
        >
          <PlusIcon className="h-6 w-6" />
        </Button>
      </div>
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Select an option</DialogTitle>
            <DialogDescription>
              Choose what you want to upload.
            </DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-3 mt-4">
            <Button
              onClick={() => {
                setDialogOpen(false);
                setModalType("files");
              }}
              variant="outline"
            >
              Upload Files
            </Button>
            <Button
              onClick={() => {
                setDialogOpen(false);
                setModalType("folder");
              }}
              variant="outline"
            >
              Add Folder
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      <Dialog open={modalType === "files"} onOpenChange={() => setModalType(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Upload Files</DialogTitle>
          </DialogHeader>
          <form className="flex flex-col gap-4">
            <input type="file" multiple ref={fileInputRef} onChange={handleFileChange} className="border rounded p-2" />
            {uploading && (
              <div className="flex flex-col gap-2">
                <Progress value={progress} className="w-full" />
                <p className="text-sm text-gray-500 text-center">{Math.round(progress)}%</p>
              </div>
            )}

            <Button type="submit" disabled={uploading} onClick={(e) => handleUpload(e)}>
              {uploading ? "Uploading..." : "Submit"}
            </Button>
          </form>
        </DialogContent>
      </Dialog>

      <Dialog open={modalType === "folder"} onOpenChange={() => setModalType(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Add Folder</DialogTitle>
          </DialogHeader>
          <form className="flex flex-col gap-4">
            <input type="text" multiple value={newFolderName} onChange={(e) => setNewFolderName(e.target.value)} className="border rounded p-2" />
            <Button type="submit" onClick={() => createFolder()}>Submit</Button>
          </form>
        </DialogContent>
      </Dialog>
    </>
  )
}
